project_id = "ljhcqubwczhtwrfpploa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.test-scan]
verify_jwt = false

[functions.perplexity-scan]
verify_jwt = false

[functions.openai-scan]
verify_jwt = false

[functions.sentiment-analysis]
verify_jwt = false

[functions.trends-analysis]
verify_jwt = false

[functions.trending-pages]
verify_jwt = false